import amelaImage from '../../../assets/tomatedulce/amela/amela1.jpg';

const BerenjenajaponesaDataPackaging = (isSpanish) => {
    return {
        Packaging: [
            {
                Packaging: isSpanish ? 'BOLSA CÓNICA CON CINTA' : 'CONICAL BAG WITH BAND',
                Presentation: '5',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X8',
                '80x120': '224',
                'Net Weight 80x120 (Kg)': '336',
                '100x120': '280',
                'Net Weight 100x120 (Kg)': '420',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'BOLSA CÓNICA CON CINTA' : 'CONICAL BAG WITH BAND',
                Presentation: '10',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '3',
                'Box size': '60X40X8',
                '80x120': '104',
                'Net Weight 80x120 (Kg)': '312',
                '100x120': '130',
                'Net Weight 100x120 (Kg)': '390',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'CINTA ENFAJADO CARTÓN' : 'CARTON BAND',
                Presentation: '5',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X8',
                '80x120': '224',
                'Net Weight 80x120 (Kg)': '336',
                '100x120': '280',
                'Net Weight 100x120 (Kg)': '420',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '2000',
                'Net Weight (kg)': '2',
                'Box size': '40X30X8',
                '80x120': '208',
                'Net Weight 80x120 (Kg)': '416',
                '100x120': '260',
                'Net Weight 100x120 (Kg)': '520',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '2500',
                'Net Weight (kg)': '2.5',
                'Box size': '40X30X9.5',
                '80x120': '176',
                'Net Weight 80x120 (Kg)': '440',
                '100x120': '220',
                'Net Weight 100x120 (Kg)': '550',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '3000',
                'Net Weight (kg)': '3',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '5000',
                'Net Weight (kg)': '5',
                'Box size': '40X30X8',
                '80x120': '224',
                'Net Weight 80x120 (Kg)': '1120',
                '100x120': '280',
                'Net Weight 100x120 (Kg)': '1400',
                Image: amelaImage,
            },
        ],
    };
};

export default BerenjenajaponesaDataPackaging;
