import amelaImage from '../../../assets/tomatedulce/amela/amela1.jpg';

const CherryDataPackaging = (isSpanish) => {
    return {
        Packaging: [
            {
                Packaging: isSpanish ? 'BOLSA SNACK EN FLOWPACK' : 'FLOWPACK SNACK BAG',
                Presentation: '25',
                'Presentation Weight (g)': '100',
                'Net Weight (kg)': '2.5',
                'Box size': '40x30x9.5',
                '80x120': '176',
                'Net Weight 80x120 (Kg)': '440',
                '100x120': '220',
                'Net Weight 100x120 (Kg)': '550',
                Image: amelaImage
              },
              {
                Packaging: isSpanish ? 'TARRINA DE CARTÓN CON TAPA' : 'CARDBOARD WITH LID',
                Presentation: '9',
                'Presentation Weight (g)': '200',
                'Net Weight (kg)': '1.8',
                'Box size': '40x30x9.5',
                '80x120': '176',
                'Net Weight 80x120 (Kg)': '316.8',
                '100x120': '220',
                'Net Weight 100x120 (Kg)': '396',
                Image: amelaImage

              },
              {
                Packaging: isSpanish ? 'TARRINA DE CARTÓN CON FLOWPACK' : 'CARDBOARD WITH FLOWPACK',
                Presentation: '9',
                'Presentation Weight (g)': '200',
                'Net Weight (kg)': '1.8',
                'Box size': '40x30x9.5',
                '80x120': '176',
                'Net Weight 80x120 (Kg)': '316.8',
                '100x120': '220',
                'Net Weight 100x120 (Kg)': '396',
                Image: amelaImage

              },
              {
                Packaging: isSpanish ? 'TARRINA DE CARTÓN CON FLOWPACK' : 'CARDBOARD WITH FLOWPACK',
                Presentation: '9',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '2.25',
                'Box size': '40X30X8',
                '80x120': '208',
                'Net Weight 80x120 (Kg)': '468',
                '100x120': '260',
                'Net Weight 100x120 (Kg)': '585',
                Image: amelaImage

              },
              {
                Packaging: isSpanish ? 'TARRINA DE CARTÓN CON FLOWPACK' : 'CARDBOARD WITH FLOWPACK',
                Presentation: '10',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '3',
                'Box size': '60X40X7',
                '80x120': '124',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '155',
                'Net Weight 100x120 (Kg)': '465',
                Image: amelaImage

              },
              {
                Packaging: isSpanish ? 'TARRINA DE CARTÓN CON FLOWPACK' : 'CARDBOARD WITH FLOWPACK',
                Presentation: '10',
                'Presentation Weight (g)': '500',
                'Net Weight (kg)': '5',
                'Box size': '60X40X8',
                '80x120': '104',
                'Net Weight 80x120 (Kg)': '520',
                '100x120': '130',
                'Net Weight 100x120 (Kg)': '650',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'BOLSA EN FLOWPACK' : 'FLOWPACK BAG',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '40X30X9.5',
                '80x120': '176',
                'Net Weight 80x120 (Kg)': '528',
                '100x120': '220',
                'Net Weight 100x120 (Kg)': '660',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA' : 'TOP SEAL PUNNET',
                Presentation: '9',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '2.25',
                'Box size': '40X30X8',
                '80x120': '224',
                'Net Weight 80x120 (Kg)': '504',
                '100x120': '280',
                'Net Weight 100x120 (Kg)': '630',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '6',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X8',
                '80x120': '224',
                'Net Weight 80x120 (Kg)': '336',
                '100x120': '280',
                'Net Weight 100x120 (Kg)': '420',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '60X40X6.2',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '5',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X7',
                '80x120': '248',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '155',
                'Net Weight 100x120 (Kg)': '232.5',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '10',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '3',
                'Box size': '60X40X7',
                '80x120': '124',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '310',
                'Net Weight 100x120 (Kg)': '930',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '10',
                'Presentation Weight (g)': '400',
                'Net Weight (kg)': '4',
                'Box size': '60X40X7',
                '80x120': '124',
                'Net Weight 80x120 (Kg)': '496',
                '100x120': '155',
                'Net Weight 100x120 (Kg)': '620',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON BISAGRA TRIANGULAR' : 'TRIANGULAR CLAMSHELL',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON BISAGRA TRIANGULAR' : 'TRIANGULAR CLAMSHELL',
                Presentation: '6',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X8',
                '80x120': '224',
                'Net Weight 80x120 (Kg)': '336',
                '100x120': '280',
                'Net Weight 100x120 (Kg)': '420',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'VASO CON TAPA' : 'SHAKER WITH LID',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '40X30X15.2',
                '80x120': '112',
                'Net Weight 80x120 (Kg)': '336',
                '100x120': '140',
                'Net Weight 100x120 (Kg)': '420',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'VASO CON TAPA' : 'SHAKER WITH LID',
                Presentation: '5',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X7',
                '80x120': '248',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '310',
                'Net Weight 100x120 (Kg)': '465',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'VASO CON TAPA' : 'SHAKER WITH LID',
                Presentation: '10',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '3',
                'Box size': '60X40X7',
                '80x120': '124',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '155',
                'Net Weight 100x120 (Kg)': '465',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'VASO APLICABLE CON VISAGRA' : 'STOCKABLE CLAMSHELL SHAKER',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA' : 'TOP SEAL PUNNET',
                Presentation: '6',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X7',
                '80x120': '248',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '310',
                'Net Weight 100x120 (Kg)': '465',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA' : 'TOP SEAL PUNNET',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA' : 'TOP SEAL PUNNET',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '60X40X6.2',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA CON ENFAJADO' : 'TOP SEAL PUNNET WITH BAND',
                Presentation: '6',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X7',
                '80x120': '248',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '310',
                'Net Weight 100x120 (Kg)': '465',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA CON ENFAJADO' : 'TOP SEAL PUNNET WITH BAND',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA CON ENFAJADO' : 'TOP SEAL PUNNET WITH BAND',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '60X40X6.2',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA PASTA CELULOSA TERMOSELLADA' : 'CELLULOSE PULP TOP SEAL PUNNET',
                Presentation: '6',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X7',
                '80x120': '248',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '310',
                'Net Weight 100x120 (Kg)': '465',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA PASTA CELULOSA TERMOSELLADA' : 'CELLULOSE PULP TOP SEAL PUNNET',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA PASTA CELULOSA TERMOSELLADA' : 'CELLULOSE PULP TOP SEAL PUNNET',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '60X40X6.2',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON TAPA' : 'PUNNET WITH LID',
                Presentation: '5',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X7',
                '80x120': '248',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '310',
                'Net Weight 100x120 (Kg)': '465',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON TAPA' : 'PUNNET WITH LID',
                Presentation: '10',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '3',
                'Box size': '60X40X7',
                '80x120': '124',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '155',
                'Net Weight 100x120 (Kg)': '465',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'CUBO CON TAPA' : 'BUCKET WITH LID',
                Presentation: '9',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '2.7',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '388.8',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '486',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA' : 'TOP SEAL PUNNET',
                Presentation: '10',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '3',
                'Box size': '60X40X7',
                '80x120': '124',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '155',
                'Net Weight 100x120 (Kg)': '465',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA PASTA CELULOSA TERMOSELLADA' : 'CELLULOSE PULP TOP SEAL PUNNET',
                Presentation: '10',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '3',
                'Box size': '60X40X7',
                '80x120': '124',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '155',
                'Net Weight 100x120 (Kg)': '465',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA PASTA CELULOSA TERMOSELLADA' : 'CELLULOSE PULP TOP SEAL PUNNET',
                Presentation: '10',
                'Presentation Weight (g)': '400',
                'Net Weight (kg)': '4',
                'Box size': '60X40X9.7',
                '80x120': '92',
                'Net Weight 80x120 (Kg)': '368',
                '100x120': '115',
                'Net Weight 100x120 (Kg)': '460',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '10',
                'Presentation Weight (g)': '500',
                'Net Weight (kg)': '5',
                'Box size': '60X40X8',
                '80x120': '104',
                'Net Weight 80x120 (Kg)': '520',
                '100x120': '130',
                'Net Weight 100x120 (Kg)': '650',
                Image: amelaImage,
              },
                                   
            ],
    };
};

export default CherryDataPackaging;
