import amelaImage from '../../../assets/tomatedulce/amela/amela1.jpg';

const MycubiesDataPackaging = (isSpanish) => {
    return {
        Packaging: [
            {
                Packaging: isSpanish ? 'VASO CON TAPA' : 'SHAKER WITH LID',
                Presentation: '12',
                'Presentation Weight (g)': '175',
                'Net Weight (kg)': '2.1',
                'Box size': '40X30X15.2',
                '80x120': '112',
                'Net Weight 80x120 (Kg)': '235.2',
                '100x120': '140',
                'Net Weight 100x120 (Kg)': '294',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'VASO APLICABLE CON VISAGRA' : 'STOCKABLE CLAMSHELL SHAKER',
                Presentation: '12',
                'Presentation Weight (g)': '175',
                'Net Weight (kg)': '2.1',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '302.4',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '378',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '6',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X8',
                '80x120': '248',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '310',
                'Net Weight 100x120 (Kg)': '465',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '60X40X6.2',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '9',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '2.25',
                'Box size': '40X30X8',
                '80x120': '224',
                'Net Weight 80x120 (Kg)': '504',
                '100x120': '280',
                'Net Weight 100x120 (Kg)': '630',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA' : 'TOP SEAL PUNNET',
                Presentation: '6',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X7',
                '80x120': '248',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '310',
                'Net Weight 100x120 (Kg)': '465',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA' : 'TOP SEAL PUNNET',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA' : 'TOP SEAL PUNNET',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '60X40X6.2',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '1500',
                'Net Weight (kg)': '1.5',
                'Box size': '30X20X8',
                '80x120': '384',
                'Net Weight 80x120 (Kg)': '576',
                '100x120': '480',
                'Net Weight 100x120 (Kg)': '720',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '2500',
                'Net Weight (kg)': '2.5',
                'Box size': '30X20X11.5',
                '80x120': '276',
                'Net Weight 80x120 (Kg)': '690',
                '100x120': '340',
                'Net Weight 100x120 (Kg)': '850',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '4000',
                'Net Weight (kg)': '4',
                'Box size': '40X30X9.4',
                '80x120': '176',
                'Net Weight 80x120 (Kg)': '704',
                '100x120': '220',
                'Net Weight 100x120 (Kg)': '880',
                Image: amelaImage,
            },
        ],
    };
};

export default MycubiesDataPackaging;
