import amelaImage from '../../../assets/tomatedulce/amela/amela1.jpg';

const PadronDataPackaging = (isSpanish) => {
    return {
        Packaging: [
            {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '5',
                'Presentation Weight (g)': '200',
                'Net Weight (kg)': '1',
                'Box size': '40X30X7',
                '80x120': '248',
                'Net Weight 80x120 (Kg)': '248',
                '100x120': '310',
                'Net Weight 100x120 (Kg)': '310',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '10',
                'Presentation Weight (g)': '200',
                'Net Weight (kg)': '2',
                'Box size': '40x30x15,5',
                '80x120': '112',
                'Net Weight 80x120 (Kg)': '224',
                '100x120': '140',
                'Net Weight 100x120 (Kg)': '280',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '10',
                'Presentation Weight (g)': '200',
                'Net Weight (kg)': '2',
                'Box size': '60x40x7',
                '80x120': '124',
                'Net Weight 80x120 (Kg)': '248',
                '100x120': '155',
                'Net Weight 100x120 (Kg)': '310',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'BOLSA EN FLOWPACK' : 'FLOWPACK BAG',
                Presentation: '10',
                'Presentation Weight (g)': '150',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '216',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '270',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'BOLSA EN FLOWPACK' : 'FLOWPACK BAG',
                Presentation: '10',
                'Presentation Weight (g)': '150',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X14',
                '80x120': '128',
                'Net Weight 80x120 (Kg)': '192',
                '100x120': '150',
                'Net Weight 100x120 (Kg)': '225',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'BOLSA EN FLOWPACK' : 'FLOWPACK BAG',
                Presentation: '5',
                'Presentation Weight (g)': '200',
                'Net Weight (kg)': '1',
                'Box size': '40X30X7',
                '80x120': '248',
                'Net Weight 80x120 (Kg)': '248',
                '100x120': '310',
                'Net Weight 100x120 (Kg)': '310',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'BOLSA EN FLOWPACK' : 'FLOWPACK BAG',
                Presentation: '6',
                'Presentation Weight (g)': '200',
                'Net Weight (kg)': '1.2',
                'Box size': '40X30X8',
                '80x120': '224',
                'Net Weight 80x120 (Kg)': '268.8',
                '100x120': '280',
                'Net Weight 100x120 (Kg)': '336',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'BOLSA EN FLOWPACK' : 'FLOWPACK BAG',
                Presentation: '10',
                'Presentation Weight (g)': '200',
                'Net Weight (kg)': '2',
                'Box size': '40X30X14',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '288',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '360',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON BISAGRA' : 'CLAMSHELL PUNNET',
                Presentation: '4',
                'Presentation Weight (g)': '650',
                'Net Weight (kg)': '2.6',
                'Box size': '60X40X12',
                '80x120': '72',
                'Net Weight 80x120 (Kg)': '187.2',
                '100x120': '90',
                'Net Weight 100x120 (Kg)': '234',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA' : 'TOP SEAL PUNNET',
                Presentation: '10',
                'Presentation Weight (g)': '200',
                'Net Weight (kg)': '2',
                'Box size': '60X40X9.7',
                '80x120': '92',
                'Net Weight 80x120 (Kg)': '184',
                '100x120': '115',
                'Net Weight 100x120 (Kg)': '230',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '10',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '2.5',
                'Box size': '40X30X15.5',
                '80x120': '112',
                'Net Weight 80x120 (Kg)': '280',
                '100x120': '140',
                'Net Weight 100x120 (Kg)': '350',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '1000',
                'Net Weight (kg)': '1',
                'Box size': '30X20X11.5',
                '80x120': '270',
                'Net Weight 80x120 (Kg)': '270',
                '100x120': '324',
                'Net Weight 100x120 (Kg)': '324',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '2000',
                'Net Weight (kg)': '2',
                'Box size': '30X20X8',
                '80x120': '384',
                'Net Weight 80x120 (Kg)': '768',
                '100x120': '480',
                'Net Weight 100x120 (Kg)': '960',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '3000',
                'Net Weight (kg)': '3',
                'Box size': '40X30X7',
                '80x120': '176',
                'Net Weight 80x120 (Kg)': '528',
                '100x120': '220',
                'Net Weight 100x120 (Kg)': '660',
                Image: amelaImage,
              },
            
        ],
    };
};

export default PadronDataPackaging;
