import amelaImage from '../../../assets/tomatedulce/amela/amela1.jpg';

const PicantesDataPackaging = (isSpanish) => {
    return {
        Packaging: [
            {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '10',
                'Presentation Weight (g)': '50',
                'Net Weight (kg)': '0.5',
                'Box size': '40X30X7',
                '80x120': '248',
                'Net Weight 80x120 (Kg)': '124',
                '100x120': '310',
                'Net Weight 100x120 (Kg)': '155',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'TARRINA DE CARTÓN CON FLOWPACK' : 'CARDBOARD WITH FLOWPACK',
                Presentation: '8',
                'Presentation Weight (g)': '80',
                'Net Weight (kg)': '0.64',
                'Box size': '40X30X7',
                '80x120': '248',
                'Net Weight 80x120 (Kg)': '158.72',
                '100x120': '310',
                'Net Weight 100x120 (Kg)': '198.4',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '12',
                'Presentation Weight (g)': '100',
                'Net Weight (kg)': '1.2',
                'Box size': '40X30X9.5',
                '80x120': '176',
                'Net Weight 80x120 (Kg)': '211.2',
                '100x120': '220',
                'Net Weight 100x120 (Kg)': '264',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'TARRINA CON BISAGRA' : 'CLAMSHELL PUNNET',
                Presentation: '8',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '2',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '288',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '360',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'TARRINA CON BISAGRA' : 'CLAMSHELL PUNNET',
                Presentation: '10',
                'Presentation Weight (g)': '500',
                'Net Weight (kg)': '5',
                'Box size': '60X40X12',
                '80x120': '72',
                'Net Weight 80x120 (Kg)': '360',
                '100x120': '90',
                'Net Weight 100x120 (Kg)': '450',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '1200',
                'Net Weight (kg)': '1.2',
                'Box size': '30X20X8',
                '80x120': '384',
                'Net Weight 80x120 (Kg)': '460.8',
                '100x120': '480',
                'Net Weight 100x120 (Kg)': '576',
                Image: amelaImage,
            },
            {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '3000',
                'Net Weight (kg)': '3',
                'Box size': '40X30X7',
                '80x120': '176',
                'Net Weight 80x120 (Kg)': '528',
                '100x120': '220',
                'Net Weight 100x120 (Kg)': '660',
                Image: amelaImage,
            },
        ],
    };
};

export default PicantesDataPackaging;
