import amelaImage from '../../../assets/tomatedulce/amela/amela1.jpg';

const TribelliDataPackaging = (isSpanish) => {
    return {
        Packaging: [
            {
                Packaging: isSpanish ? 'VASO CON TAPA' : 'SHAKER WITH LID',
                Presentation: '12',
                'Presentation Weight (g)': '150',
                'Net Weight (kg)': '1.8',
                'Box size': '40X30X15.2',
                '80x120': '112',
                'Net Weight 80x120 (Kg)': '201.6',
                '100x120': '140',
                'Net Weight 100x120 (Kg)': '252',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'VASO APLICABLE CON VISAGRA' : 'STOCKABLE CLAMSHELL SHAKER',
                Presentation: '12',
                'Presentation Weight (g)': '150',
                'Net Weight (kg)': '1.8',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '259.2',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '324',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '9',
                'Presentation Weight (g)': '150',
                'Net Weight (kg)': '1.35',
                'Box size': '40X30X8',
                '80x120': '208',
                'Net Weight 80x120 (Kg)': '280.8',
                '100x120': '260',
                'Net Weight 100x120 (Kg)': '351',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '12',
                'Presentation Weight (g)': '150',
                'Net Weight (kg)': '1.8',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '259.2',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '324',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '12',
                'Presentation Weight (g)': '150',
                'Net Weight (kg)': '1.8',
                'Box size': '60X40X7',
                '80x120': '124',
                'Net Weight 80x120 (Kg)': '223.2',
                '100x120': '155',
                'Net Weight 100x120 (Kg)': '279',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON FLOWPACK' : 'PUNNET WITH FLOWPACK',
                Presentation: '10',
                'Presentation Weight (g)': '350',
                'Net Weight (kg)': '3.5',
                'Box size': '60X40X8',
                '80x120': '104',
                'Net Weight 80x120 (Kg)': '364',
                '100x120': '130',
                'Net Weight 100x120 (Kg)': '455',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA' : 'TOP SEAL PUNNET',
                Presentation: '6',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '1.5',
                'Box size': '40X30X7',
                '80x120': '248',
                'Net Weight 80x120 (Kg)': '372',
                '100x120': '310',
                'Net Weight 100x120 (Kg)': '465',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA' : 'TOP SEAL PUNNET',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '40X30X12',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA' : 'TOP SEAL PUNNET',
                Presentation: '12',
                'Presentation Weight (g)': '250',
                'Net Weight (kg)': '3',
                'Box size': '60X40X6.2',
                '80x120': '144',
                'Net Weight 80x120 (Kg)': '432',
                '100x120': '180',
                'Net Weight 100x120 (Kg)': '540',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA TERMOSELLADA' : 'TOP SEAL PUNNET',
                Presentation: '10',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '3',
                'Box size': '60X40X9.7',
                '80x120': '92',
                'Net Weight 80x120 (Kg)': '276',
                '100x120': '115',
                'Net Weight 100x120 (Kg)': '345',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA DE CARTÓN CON FLOWPACK' : 'CARDBOARD WITH FLOWPACK',
                Presentation: '8',
                'Presentation Weight (g)': '150',
                'Net Weight (kg)': '1.2',
                'Box size': '40X30X8',
                '80x120': '208',
                'Net Weight 80x120 (Kg)': '249.6',
                '100x120': '260',
                'Net Weight 100x120 (Kg)': '312',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA PASTA CELULOSA TERMOSELLADA' : 'CELLULOSE PULP TOP SEAL PUNNET',
                Presentation: '10',
                'Presentation Weight (g)': '200',
                'Net Weight (kg)': '2',
                'Box size': '60X40X7',
                '80x120': '124',
                'Net Weight 80x120 (Kg)': '248',
                '100x120': '155',
                'Net Weight 100x120 (Kg)': '310',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'BOLSA EN FLOWPACK' : 'FLOWPACK BAG',
                Presentation: '10',
                'Presentation Weight (g)': '200',
                'Net Weight (kg)': '2',
                'Box size': '40X30X9.5',
                '80x120': '176',
                'Net Weight 80x120 (Kg)': '352',
                '100x120': '220',
                'Net Weight 100x120 (Kg)': '440',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'TARRINA CON BISAGRA' : 'CLAMSHELL PUNNET',
                Presentation: '8',
                'Presentation Weight (g)': '680',
                'Net Weight (kg)': '5.44',
                'Box size': '60X40X12',
                '80x120': '72',
                'Net Weight 80x120 (Kg)': '391.68',
                '100x120': '90',
                'Net Weight 100x120 (Kg)': '489.6',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'CUBO CON TAPA' : 'BUCKET WITH LID',
                Presentation: '14',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '4.2',
                'Box size': '60X40X15',
                '80x120': '56',
                'Net Weight 80x120 (Kg)': '235.2',
                '100x120': '70',
                'Net Weight 100x120 (Kg)': '294',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'CUBO CON TAPA' : 'BUCKET WITH LID',
                Presentation: '6',
                'Presentation Weight (g)': '300',
                'Net Weight (kg)': '1.8',
                'Box size': '40X30X14',
                '80x120': '128',
                'Net Weight 80x120 (Kg)': '230.4',
                '100x120': '150',
                'Net Weight 100x120 (Kg)': '270',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '1000',
                'Net Weight (kg)': '1',
                'Box size': '30X20X8',
                '80x120': '384',
                'Net Weight 80x120 (Kg)': '384',
                '100x120': '480',
                'Net Weight 100x120 (Kg)': '480',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '1500',
                'Net Weight (kg)': '1.5',
                'Box size': '30X20X11.5',
                '80x120': '276',
                'Net Weight 80x120 (Kg)': '414',
                '100x120': '340',
                'Net Weight 100x120 (Kg)': '510',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '2000',
                'Net Weight (kg)': '2',
                'Box size': '40X30X8',
                '80x120': '208',
                'Net Weight 80x120 (Kg)': '416',
                '100x120': '260',
                'Net Weight 100x120 (Kg)': '520',
                Image: amelaImage,
              },
              {
                Packaging: isSpanish ? 'GRANEL' : 'LOOSE',
                Presentation: '1',
                'Presentation Weight (g)': '3000',
                'Net Weight (kg)': '3',
                'Box size': '40X30X9.5',
                '80x120': '176',
                'Net Weight 80x120 (Kg)': '528',
                '100x120': '220',
                'Net Weight 100x120 (Kg)': '660',
                Image: amelaImage,
              },            
        ],
    };
};

export default TribelliDataPackaging;
